api/urls.py
from django.urls import path, include
from .views import BookListView
from catalog.views import *
from rest_framework import routers
from catalog.views import *

router = routers.DefaultRouter()
router.register('categories', CategoryViewSet, basename='category')
router.register('comments', CommentViewSet)
# router.register('reports', ReportViewSet, basename='report')

urlpatterns = [
    path('', include(router.urls)),
    path('reports/', ReportViewSet.as_view()),
    # path('chat/', ChatViewSet.as_view()),
    # path('hello/', BookListView.as_view(), name='hello'),
]

app/urls.py
# django_project/urls.py
from django.urls import path, include, re_path  # new
from django.views.generic.base import TemplateView  # new
from django.conf import settings
from django.conf.urls.static import static
# from catalog.admin import admin_site
from drf_yasg import openapi
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from app.views import HomeView
from django.contrib import admin 

schema_view = get_schema_view(
   openapi.Info(
      title="Your API",
      default_version='v1',
      description="API documentation",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('accounts/', include('allauth.urls')), # login google
    path("accounts/", include("accounts.urls")),  # signup
    path("accounts/", include("django.contrib.auth.urls")),  # login,logout
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(template_name="home.html"), name="home"),  # new
    path("catalog/", include('catalog.urls')),
    path('api/', include('api.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # Endpoint để lấy token
    path('api/token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # Endpoint để làm mới token
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         re_path(r'^__debug__/', include(debug_toolbar.urls)),  # updated
#     ] + urlpatterns

user/urls.py
# django_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path  # new
from django.views.generic.base import TemplateView  # new
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),  # signup
    path("accounts/", include("django.contrib.auth.urls")),  # login,logout
    path("", TemplateView.as_view(template_name="home.html"), name="home"),  # new
    path("categories", include('catalog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         re_path(r'^__debug__/', include(debug_toolbar.urls)),  # updated
#     ] + urlpatterns

catalog/models.py
# categories/models.py
import sys
from django.contrib.auth.models import AbstractUser
from django.db import models
import os
from PIL import Image as PilImage
from io import BytesIO
from django.core.files import File
from ckeditor.fields import RichTextField

class itemBase(models.Model): # abstract base class
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True

class Category(itemBase):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='categories/%Y/%m', null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=False)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return str(self.name)
    def get_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return ''  # replace with the path to your default image
    
    def delete(self, *args, **kwargs):
        print('image',self.image.path)
        if os.path.isfile(self.image.path):
            os.remove(self.image.path)
        super().delete(*args, **kwargs)

class Product(itemBase):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='')
    categories = models.ManyToManyField(Category, related_name='products')
    view = models.IntegerField(default=0)
    content = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    def delete(self, *args, **kwargs):
        print('image',self.image.path)
        if os.path.isfile(self.image.path):
            os.remove(self.image.path)
        super().delete(*args, **kwargs)
    
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # save thumbnail
        if self.image: 
            img = PilImage.open(self.image.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                thumb_io = BytesIO()
                img.save(thumb_io, img.format)
                file_name = self.image.name.split('/')[-1]

                self.image.save(
                    file_name,
                    File(thumb_io),
                    save=False,
                )

        super().save(*args, **kwargs)


class Image(itemBase):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    pic = models.FileField(upload_to='products/')
class Comment(itemBase):
    name = models.CharField(max_length=100)
    comment = models.TextField(max_length=100)
    product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.name
    

class Reply(itemBase):
    name = models.CharField(max_length=100)
    content = models.TextField(max_length=100)
    comment = models.ForeignKey(Comment, related_name='replies', on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.name
    
class Slider(itemBase):
    image = models.ImageField(upload_to='slider/')
    description = models.CharField(max_length=100)
    def __str__(self):
        return self.description

templates/layout/navbar.html
  <div class="bg-danger fontStyle2 mt-2">
    <button type="button" data-bs-toggle="collapse" data-bs-target="#bottomNavbar" class="btn btn-danger w-100 d-lg-none d-md-none d-sm-block d-xs-block rounded-0 p-2"><i class="fas fa-bars me-2"></i> Menu</button>
    <div class="collapse navbar-collapse px-2" id="bottomNavbar">
      <div class="container-fluid">
        <div class="d-flex justify-content-between align-items-center" id="removeFlex">
          <div class="flex-grow-1">
            <a href="{% url 'home' %}" class="{%if request.path == '/'%} active {%endif%} d-inline-block customNav">Home</a>
            <a href="{% url 'category_list' %}" class="{%if 'categories' in request.path %} active {%endif%} d-inline-block customNav">Categories</a>
            <a href="{% url 'product_list' %}" class="{%if 'products' in request.path %} active {%endif%} d-inline-block customNav">Products</a>
            <a href="{% url 'signup' %}" class="{%if 'signup' in request.path %} active {%endif%} d-inline-block customNav">Signup</a>
            <a href="{% url 'reports' %}" class="{%if 'reports' in request.path %} active {%endif%} d-inline-block customNav">Report</a>
            <a href="{% url 'chat' %}" class="{%if 'chat' in request.path %} active {%endif%} d-inline-block customNav">Chat</a>
            <a href="/admin" class="d-inline-block customNav">Admin</a>
          </div>
          <div class="">
            <i class="fas fa-search text-white fs-6"></i>
            {% if user.is_authenticated %}
            <a href="#" class="customNav">Welcome, {{ user.first_name }}  {{user.last_name}}!</a>
                {% if user.socialaccount_set.all.0.provider == 'google' %}
                <a  href="#"><img src="{{ user.socialaccount_set.all.0.extra_data.picture }}" alt="{{ user.username }}" class="rounded-circle img-responsive" width="50" height="50"></a>
                {% elif user.socialaccount_set.all.0.provider == 'facebook' %}
                <a  href="#"><img src="{{ user.socialaccount_set.all.0.extra_data.picture.data.url }}" alt="{{ user.username }}" class="rounded-circle img-responsive" width="50" height="50"></a>
                {% endif %}
                <form action="{% url 'logout' %}" method="post" class="float-right">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger mt-2 ml-1 compact">Log Out</button>
                </form>
            {%else%}
            <a href="{% url 'login' %}" class="btn btn-danger mt-2 ml-1 compact">Log In</a>
            {%endif%}
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    // document.addEventListener('DOMContentLoaded', (event) => {
    //   const token = document.cookie.split('; ').find(row => row.startsWith('token')).split('=')[1];
    //   const authSection = document.getElementById('authSection');

    //   if (token) {
    //     authSection.innerHTML = `
    //       <form action="{% url 'logout' %}" method="post">
    //         {% csrf_token %}
    //         <button type="submit" class="btn btn-outline-danger pt-2 px-4 compact">Log Out</button>
    //       </form>
    //     `;
    //   } else {
    //     authSection.innerHTML = `
    //       <a href="{% url 'login' %}" class="btn btn-outline-danger pt-2 px-4 compact">Log In</a>
    //     `;
    //   }
    // });
  </script>

  <div id="authSection"></div>

templates/layout/slider.html
{% load static %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        {% for slider in sliders %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}" data-interval="3000">
                <img class="d-block w-100" src="{{slider.image.url }}" alt="{{ slider.description }}" style="max-height: 670px; object-fit: cover;">
                <div class="carousel-caption d-none d-md-block">
                    <p>{{ slider.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>